config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :skatespots, only: [:index, :show, :create, :new, :edit] do
    resources :conversations, only: :create
  end
  get 'dashboard', to: 'pages#dashboard'
  resources :articles, only: [:index, :create, :new, :edit, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo
  validates :name, presence: true
  validates :content, presence: true
  # validates :password, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :skatespot
  belongs_to :user
  validates :content, length: { minimum: 1 }
  has_one_attached :photo
end

app/models/skatespot.rb
class Skatespot < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
  has_many :conversations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # For localisation User
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :conversations
  # Validates conditions
  validates :username, length: { minimum: 5 }
  # Media rattached
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :photo) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :photo ) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :content)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create

  def create
    @conversation = Conversation.new(conversation_params)
    @skatespot = Skatespot.find(params[:skatespot_id])
    @conversation.skatespot = @skatespot
    @conversation.user = current_user

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to skatespot_path(@skatespot) }
        format.json
      else
        format.html { render "skatespots/show", status: :unprocessable_entity }
        format.json
      end
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:content, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @skatespots = Skatespot.all
  end

  def dashboard
    @user = current_user
  end

  def actuality
  end
end

app/controllers/skatespots_controller.rb
class SkatespotsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  
  def index
    @skatespots = Skatespot.all

    @markers = @skatespots.geocoded.map do |skatespot|
      {
        lat: skatespot.latitude,
        lng: skatespot.longitude,
        info_window: render_to_string(partial: "info_window", locals: { skatespot: skatespot }),
      }
    end
  end

  def show
    @skatespot = Skatespot.find(params[:id])
    @conversation = Conversation.new
  end

  def geolocation
    current_user.update(latitude: params[:latitude])
    current_user.update(longitude: params[:longitude])
  end

  def new
    @skatespot = Skatespot.new
  end

  def create
    @skatespot = Skatespot.new(skatespot_params)

    if @skatespot.save
      redirect_to @skatespot
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @skatespot = Skatespot.find(params[:id])
    @skatespot.destroy
    redirect_to '/skatespots/new', :notice => "Your skatespot has been deleted"
  end

  private

  def skatespot_params
    params.require(:skatespot).permit(:name, :address, :photo)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<% if current_user.email == 'admin@gmail.com' %>
  <div class="article-admin">
    <div>
      <%= link_to "Nouvel article", new_article_path, class: "btn btn-link m-2" %>
    </div>
    <% @articles.each do |article| %>
      <div class="article">
        <div class="article-name">
          <%= article.name %>
        </div>
        <div class="article-content">
          <%= article.content %>
          <div class="article-delete">
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div>
    <h2>Article</h2>
  </div>
  <% @articles.each do |article| %>
      <div class="article">
        <div class="article-name">
          <%= article.name %>
        </div>
        <div class="article-content">
          <%= article.content %>
        </div>
      </div>
    <% end %>
<% end %>

app/views/articles/new.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.input :name, placeholder: 'name article'%>
  <%= f.input :content, placeholder: 'Content', as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/conversations/_form.html.erb
<%= simple_form_for([ skatespot, conversation ],
                    data: {
                      insert_in_list_target: "form",
                      action: "submit->insert-in-list#send"
                    }) do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skatemap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render "shared/navbar" %>
    <%= yield %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>


  </body>
</html>

app/views/pages/actuality.html.erb
<% if current_user.email == 'admin@gmail.com' %>
  add article
<% else %>
  <h2>Event</h2>
<% end %>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-4">
      <h1>Username: <%= @user.username %></h1>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key,class:"rounded-circle", style: "width: 400px; height:400px;" %>
      <% else %>
        <%= image_tag "https://upload.wikimedia.org/wikipedia/fr/b/b1/Spitfire_Logo.jpg",class:"rounded-circle", style: "width: 400px; height:400px;" %>
      <% end %>
      <%= link_to "Edit your profile", edit_user_registration_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="connect" data-controller="hello"></div>
<div id='banner'>
  <img src="https://res.cloudinary.com/baptistev/image/upload/v1662639968/P1060849_ne2vwe.jpg" alt="">
</div>
<div id='presentation'>
  <h1><u>Présentation</u></h1>
  <h3>
    Bercy zoo est une association de skate ce trouvant au skate park de Bercy à Paris 12</br>
    Cette association propose des cours de skate ouvert à tous</br>
    ainsi que des évènements
  </h3>
</div>
<div id='card'>
  <div class="row justify-content-around">
    <div class="col-4">
      <div class="asso">
        <a href="#"><i class="fas fa-users"></i></a>
      </div>
    </div>
    <div class="col-4">
      <div class='skatemap'>
        <%= link_to skatespots_path do %>
          <i class="fas fa-map"></i>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <div class="article">
      <%= link_to articles_path do %>
          <i class="fas fa-file-alt"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>
 <div class="row justify-content-md-center">
      <div id="carouselExampleIndicators" class="carousel slide " data-bs-ride="carousel">
        <div class="carousel-inner mt-3">
          <% @skatespots.each_with_index do |skatespot, i| %>
            <div class="carousel-item <%= "active" if i == 0 %>">
              <a href=<%= skatespot_path(skatespot) %>>
                <%= cl_image_tag skatespot.photo.key, class:"d-block w-100 img-show" %>
              </a>
            </div>
          <% end %>
        </div>
        <% if @skatespots.count > 1 %>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        <% end %>
      </div>
    </div>
  </div>


<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/bercy_zoo/?hl=fr"><i class="fab fa-instagram"></i></a>
  </div>
  <div class='mail' data-controller='mail'>
    <form action="sendMail();">
     mail
    </form>
  </div>
  <div class="footer-copyright">
    Bercy zoo © 2022
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag "logo.png", alt: "Bercy logo", width: 75 %>
  <div class="title">
    <a href="<%= root_path %>">Bercy Zoo</a>
  </div>
  <input type="checkbox" id="toggler">
  <label for="toggler">
  <% if user_signed_in? && current_user.photo.attached? %>
     <i class="fa fa-bars fa-lg"></i></label>
    <div class="menu">
      <ul class='list'>
        <li><a href=<%= dashboard_path%>><%= cl_image_tag current_user.photo.key, class:"avatar" %></a></li>
        <li><a href= <%= skatespots_path %>>Spots</a></li>
        <li><a href=<%= new_skatespot_path %>>Ajoute un spot</a></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  <% elsif user_signed_in? %>
    <i class="fa fa-bars fa-lg"></i></label>
    <div class="menu">
      <ul class='list'>
        <li><a href=<%= dashboard_path%>>Profil</a></li>
        <li><a href= <%= skatespots_path %>>Spots</a></li>
        <li><a href=<%= new_skatespot_path %>>Ajoute un spot</a></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  <% else %>
    <i class="fa fa-bars fa-lg"></i></label>
    <div class="menu">
      <ul class='list'>
        <li><a href="<%= skatespots_path%>">Spots</a></li>
        <li><%= link_to "Login", new_user_session_path%></li>
      </ul>
  </div>
  <% end %>

</div>

app/views/skatespots/_conversation.html.erb
<p id="conversation-<%= conversation.id %>"><%= conversation.content %></p>

app/views/skatespots/_info_window.html.erb
<div class="window">
  <%= link_to skatespot, class:"card-skatespot" do %>
      <%= cl_image_tag skatespot.photo.key %>
      <h2><%= skatespot.name %></h2>
      <p>📍<%= skatespot.address %></p>
    <% end %>
</div>

app/views/skatespots/index.html.erb
<div class="container">
  <div class="map"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
 
<div>

app/views/skatespots/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 m-3">
      <%= simple_form_for(@skatespot) do |f| %>
        <%= f.input :name, placeholder: "Rodney Mullen" %>
        <%= f.input :address,
                    input_html: { data: { geocoder_target: "address" }, class: "d-none" },
                    wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } }%>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

app/views/skatespots/show.html.erb
<div class="container">
  <div class="m-3 card-skatespot ">
    <div class="card-show">
      <%= cl_image_tag @skatespot.photo.key %>
      <div class="card-skatespot-infos">
        <div>
          <h1 class="m-3"><%= @skatespot.name %></h1>
          <h2 class="m-3"><%= @skatespot.address %></h2>
          <p></p>
        </div>
      </div>
    </div>
  </div>
  <div id="conversations">
    <% if @skatespot.conversations.blank? %>
      Lache le premier msg sur <%= @skatespot.name %>
    <% else %>
      <div class="scroll-container">

          <% @skatespot.conversations.each do |conversation| %>
            <% if conversation.user == current_user %>
              <div class="message-user">
                <p id="conversation-<%= conversation.id %>">
                  <% if conversation.photo.attached? %>
                    <%= conversation.content %>
                    <%= cl_image_tag conversation.photo.key %>
                  <% else %>
                    <%= conversation.content %>
                  <% end %>
                </p>
              </div>
            <% else %>
              <div class="message-other">
                <p id="conversation-<%= conversation.id %>">
                  <% if conversation.photo.attached? %>
                    <%= conversation.content %>
                    <%= cl_image_tag conversation.photo.key %>
                  <% else %>
                    <%= conversation.content %>
                  <% end %>
                  <%= conversation.user.username %>
                </p>
              </div>
            <% end %>
          <% end %>
      </div>
    <% end %>
      <div class="form">
        <%= simple_form_for([ @skatespot, @conversation ]) do |f| %>
          <div class="button-form">
            <%= f.input :content, as: :text %>
            <div class='button-column'>
              <span class="file-wrapper">
                <span class="button", style="width: 20px">
                  <i class="fas fa-camera"></i>
                  <%= f.input :photo %>
                </span>
              </span>
              <%= f.button :submit,"Envoyer" %>
            </div>
          </div>
        <% end %>
      </div>
  </div>
  <%#   <%= link_to "Delete", skatespot_path(@skatespot), :confirm => "Are you sure?", :method => :delete %>